"""empty message

Revision ID: 466a1720af12
Revises: None
Create Date: 2013-09-26 16:13:47.395767

"""

# revision identifiers, used by Alembic.
revision = '466a1720af12'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=32), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poem')
    ### end Alembic commands ###
